//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNA.Resources.ConsoleMessages", typeof(ConsoleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling Program....
        /// </summary>
        internal static string CLI_COMPILING {
            get {
                return ResourceManager.GetString("CLI_COMPILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find file:.
        /// </summary>
        internal static string CLI_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLI_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done with file.\n.
        /// </summary>
        internal static string CLI_FINISHED_FILE {
            get {
                return ResourceManager.GetString("CLI_FINISHED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished, press enter to exit....
        /// </summary>
        internal static string CLI_FINISHED_FILES {
            get {
                return ResourceManager.GetString("CLI_FINISHED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input only BNA code or only a filename..
        /// </summary>
        internal static string CLI_INPUT_ONE_ONLY {
            get {
                return ResourceManager.GetString("CLI_INPUT_ONE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file....
        /// </summary>
        internal static string CLI_READING_FILE {
            get {
                return ResourceManager.GetString("CLI_READING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to continue (use &apos;~&apos; to exit)..
        /// </summary>
        internal static string CLI_RUN_INPUT_DONE {
            get {
                return ResourceManager.GetString("CLI_RUN_INPUT_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nInsert BNA code to do stuff or type &apos;$filename.bna&apos; to run a file (use &apos;~&apos; to end):.
        /// </summary>
        internal static string CLI_RUN_INPUT_START {
            get {
                return ResourceManager.GetString("CLI_RUN_INPUT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nRunning Program...\n.
        /// </summary>
        internal static string CLI_RUNNING {
            get {
                return ResourceManager.GetString("CLI_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ================================================================================.
        /// </summary>
        internal static string CLI_SEPARATOR_LINE {
            get {
                return ResourceManager.GetString("CLI_SEPARATOR_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the BNA&apos;s Not Assembly Interpreter!.
        /// </summary>
        internal static string CLI_WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("CLI_WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
